### ISSUE TITLE
想新增功能

### ISSUE THREAD

**Issue by wulukewu** [rayhuang2006/Grade-Caculator#1]
### 可以加地科成績嗎？

當然可以！如果你希望將地理科目的成績納入評分系統中，希望你可以根據不同的需求來進行調整。這可能涉及以下幾個方面：

1. **成績統整：** 如果你已經有了地理科目的成績，希望你可以將這些成績與其他科目的資料一同整合，並確保所有的數據都能夠精確呈現。
   
2. **加權計算：** 在某些情況下，可能需要根據特定的規則或比重來加權計算各科成績，包括地理科目。這樣可以讓最終的評分結果更為公平且符合需求。

3. **報告輸出：** 一旦成績統整完成，希望你也可以幫助你生成報告，讓成績的分佈、加權結果及每科的具體分數一目瞭然，方便查看或分享。

若有任何關於如何納入或加算地理科成績的具體要求，隨時告訴我，希望你可以根據你的需求進行個性化調整！

**Comment by rayhuang2006** [comment]
Finish!
